---
version: 2
updates:
- package-ecosystem: "gomod"
  directories:
    - /test/integration
  groups:
    minor-and-patch:
      applies-to: version-updates
      update-types:
      - "minor"
      - "patch"
  schedule:
    interval: "weekly"
    time: "09:00"
    timezone: "Europe/Oslo"
    day: "monday"
  open-pull-requests-limit: 2
- package-ecosystem: terraform
  directories:
  - /examples/minimal
  - /examples/minimal_custom_vpc
  - /examples/minimal_test
  - /modules/redis
  schedule:
    interval: "daily"
    time: "09:00"
    timezone: "Europe/Oslo"
  open-pull-requests-limit: 0  # Security-updates only
