name: Terraform Integration Tests

on:
  pull_request:
    paths:
      - "modules/redis/**"
      - "test/**"
    branches:
      - main
    types:
      - opened
      - synchronize
      - ready_for_review
  workflow_dispatch:

jobs:
  terratest_redis:
    permissions:
      contents: "read"
      id-token: "write"

    name: Integration test Redis module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.19

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5
          terraform_wrapper: false

      - id: auth
        name: Cloud Auth
        uses: entur/gha-meta/.github/actions/cloud-auth@v1
        with:
          environment: dev
          gcp_workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          gcp_service_account: ${{ vars.SERVICE_ACCOUNT }}

      - name: Kubernetes Auth
        uses: entur/gha-meta/.github/actions/k8s-auth@v1
        with:
          environment: dev

      - name: Download Go Modules
        working-directory: test/integration
        run: go mod download

      - name: Run Go Integration Tests
        working-directory: test/integration
        run: go test -tags=integration -timeout 30m
