name: Terraform Unit Tests

on:
  push:
    paths:
      - 'modules/redis/**'
      - 'tests/**'
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - ready_for_review
  workflow_dispatch:

jobs:
  terratest_redis:
    permissions:
      contents: 'read'
      id-token: 'write'

    name: Unit test Redis module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.5
          terraform_wrapper: false
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{ secrets.PROVIDER_NAME }}
          service_account: ${{ secrets.SA_EMAIL }}
      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v0'
        with:
          project_id: ${{ secrets.CLUSTER_PROJECT_ID }}
          cluster_name: ${{ secrets.CLUSTER_NAME }}
          location: ${{ secrets.CLUSTER_LOCATION }}
      - name: Download Go Modules
        working-directory: tests
        run: go mod download
      - name: Run Go Unit Tests
        working-directory: tests
        run: go test -tags=unit -timeout 30m
